# Generated by Django 4.2.23 on 2025-09-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
