# Generated by Django 4.2.23 on 2025-09-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
